# Generated by Django 4.2.8 on 2023-12-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FestPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('yearofstudy', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_number', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('staff_or_student', models.CharField(max_length=100)),
                ('gitamite_or_nongitamite', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('yearofstudy', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_number', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('staff_or_student', models.CharField(max_length=100)),
                ('gitamite_or_nongitamite', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=100)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
