# Generated by Django 4.2.8 on 2023-12-07 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('task_title', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('president', 'President'), ('vice-president', 'Vice President'), ('technology', 'Technology'), ('events-cultural', 'Events - Cultural'), ('events-sports', 'Events - Sports'), ('legal', 'Legal'), ('operations', 'Operations'), ('marketing', 'Marketing'), ('sponsorship', 'Sponsorship'), ('design', 'Design'), ('finance', 'Finance'), ('media', 'Media'), ('security', 'Security'), ('hospitality', 'Hospitality')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
