# Generated by Django 4.2.8 on 2023-12-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreteam', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
