# Generated by Django 4.2.8 on 2023-12-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreteam', '0004_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_design',
            new_name='design',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_events_cultural',
            new_name='events_cultural',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_events_sports',
            new_name='events_sports',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_finance',
            new_name='finance',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_hospitality',
            new_name='hospitality',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_legal',
            new_name='legal',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_marketing',
            new_name='marketing',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_media',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_operations',
            new_name='operations',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_president',
            new_name='president',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_security',
            new_name='security',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_sponsorship',
            new_name='sponsorship',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_technology',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_vice_president',
            new_name='vice_president',
        ),
        migrations.AddField(
            model_name='task',
            name='advisory',
            field=models.BooleanField(default=False),
        ),
    ]
