# Generated by Django 4.2.8 on 2023-12-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreteam', '0005_rename_is_design_customuser_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='advisory',
            field=models.BooleanField(default=False),
        ),
    ]
