# Generated by Django 4.2.8 on 2023-12-20 13:10

import coreteam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreteam', '0006_customuser_advisory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='events_cultural_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='events_sports_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hospitality_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=coreteam.models.file_upload_path),
        ),
    ]
