# Generated by Django 4.2.8 on 2023-12-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='reference_attatchment',
            field=models.FileField(blank=True, null=True, upload_to='prelims_files/'),
        ),
    ]
