# Generated by Django 4.2.8 on 2023-12-26 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prelims', '0002_alter_team_reference_attatchment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain_regnum',
        ),
        migrations.AddField(
            model_name='team',
            name='captain_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
