# Generated by Django 4.2.8 on 2023-12-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prelims', '0003_remove_team_captain_regnum_team_captain_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teammates',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
