# Generated by Django 4.2.8 on 2024-01-25 02:05

from django.db import migrations, models
import promotion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BGMIPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('regno', models.CharField(max_length=100)),
                ('yearofstudy', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('regno', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('Campus', models.CharField(max_length=50)),
                ('ishosteler', models.BooleanField(default=False)),
                ('previous_experience', models.TextField()),
                ('availability', models.TextField()),
                ('why_you_interested', models.TextField()),
                ('tshirt_size', models.CharField(max_length=30)),
                ('domain_of_interest', models.CharField(max_length=150)),
                ('isvolunteer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(upload_to=promotion.models.profilepic_upload_path)),
            ],
        ),
    ]
