# Generated by Django 4.2.8 on 2023-12-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgmiplayer',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
