# Generated by Django 4.2.8 on 2023-12-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('meal_id', models.IntegerField(blank=True, null=True)),
                ('qr_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('checkin', models.DateTimeField(blank=True, null=True)),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('hostel', models.CharField(blank=True, choices=[('RBS', 'Rabindranath Sadan'), ('RBS-AC', 'Rabindranath Tagore Sadan AC'), ('VS', 'Vinay Sadan'), ('NS', 'Nirmala Sadan'), ('NS-AC', 'Nirmala Sadan AC'), ('KS', 'Kokila Sadan'), ('KS-AC', 'Kokila Sadan AC')], max_length=255, null=True)),
                ('room_number', models.IntegerField(blank=True, null=True)),
                ('checkin_status', models.BooleanField(blank=True, default=False, null=True)),
                ('checkout_status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Hi-Tea', 'Hi-Tea'), ('Dinner', 'Dinner')], max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_time', models.DateTimeField(auto_now_add=True)),
                ('meal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitality.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitality.hospitalityuser')),
            ],
        ),
    ]
