# Generated by Django 4.2.8 on 2023-12-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalityuser',
            name='user_id',
        ),
    ]
